#!/usr/bin/env bash
# A bash script to install nginx and configure a hello world site
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello world" > /var/www/html/index.html
service nginx restart
