#!/usr/bin/env bash
# setup load balancer
apt update
apt install -y haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
configf=$'\nfrontend web-frontend\n\tbind localhost:80\n\tmode http\n\tdefault_backend web-backend'
configb=$'\nbackend web-backend\n\tbalance roundrobin\n\tserver web-01 \t100.26.135.224:80 check\n\tserver web-02 \t3.235.226.56:80 check'
echo "$configf" >> /etc/haproxy/haproxy.cfg
echo "$configb" >> /etc/haproxy/haproxy.cfg
service haproxy restart
