#!/usr/bin/env bash
# make nginx listen on a port
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default ; sed -i 's/ ipv6only=on//g' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//g' /etc/nginx/sites-available/default
service nginx restart
