#!/usr/bin/env bash
# A script that prints numbers and some superstious numbers as well

i=1
while [ $i -lt 21 ]; do
	case $i in
		4)
			echo $i
			echo 'bad luck from China'
			;;
		9)
			echo $i
			echo 'bad luck from Japan'
			;;
		17)
			echo $i
			echo 'bad luck from Italy'
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done
